### ISSUE TITLE
Error when having Chinese character in source file on Windows.

### ISSUE THREAD

**Issue by Krantz-XRF** [lunaryorn/vscode-hlint#12]
I meet error message whenever I have Chinese character in my source file, even if those character is in the comment. I use `stack 1.7.1` and `HLint 2.1.3` on `Windows 10`, the default code page should be `GBK` or something similar. 
Here's the error message:
> Error: Command failed: stack exec -- hlint --no-exit-code --json - hlint.EXE: <stdin>: hGetContents: invalid argument (invalid byte sequence)

However, when I run hlint in the terminal, I won't get any error message, HLint just exits normally.

**Comment by lunaryorn** [comment]
@Krantz-XRF I am sorry but I cannot fix this issue myself.  I have no access to a Windows system nor can I easily setup a Chinese language environment somewhere.  

I am afraid you will have to debug this issue yourself.  I welcome a pull request to fix it.

Meanwhile though I will close this ticket since I will not work on it myself.
